export type CategoryId = "skin" | "body" | "hair" | "foot";
export type TierId = "teen" | "divine" | "golden" | "timeless";
export type ProductKey = `${CategoryId}-${TierId}`;

export interface Product {
  name: string;
  desc: string;
  ingredients: string;
  benefits: string;
  oily: string;
  dry: string;
  normal:string;
  combination:string;
  tag: string;
  price: string;
  image: string;
}
export const slugify = (name: string): string =>
  name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const img = (name: string): string => `/images/products/${slugify(name)}.jpg`;

/* ---------------------------------------------------------
Eudora Naturals — a standalone line, filtered by product
type only (Sheet Masks / Face Scrub). No age tiers apply.
--------------------------------------------------------- */

export type EudoraSubId = "sheet-mask" | "face-scrub";

export const EUDORA_PRODUCTS: Record<EudoraSubId, Product[]> = {
  "sheet-mask": [
    {
      name: "Eudora Apaisement Aloe Vera Mask",
      desc: "A soothing, cooling gel mask for calm, hydrated skin.",
      ingredients: "Ingredients: Aloe vera gel, Hyaluronic acid, Chamomile extract, Vitamin E",
      benefits: "Benefits: Calms redness and irritation, deeply hydrates, soothes sun-exposed or sensitive skin, leaves skin soft and refreshed.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "650.00",
      image: img("Eudora Apaisement Aloe Vera Mask"),
    },
    {
      name: "Eudora Vitalité Beetroot Mask",
      desc: "A revitalizing mask that restores color and life to tired skin.",
      ingredients: "Ingredients: Beetroot extract, Vitamin C, Hyaluronic acid, Aloe vera",
      benefits: "Benefits: Boosts circulation for a natural flush, brightens dull and tired-looking skin, rich in antioxidants, restores a healthy glow.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "650.00",
      image: img("Eudora Vitalité Beetroot Mask"),
    },
    {
      name: "Eudora Agrume Orange Mask",
      desc: "A citrus-brightening mask for radiance and even tone.",
      ingredients: "Ingredients: Orange extract, Vitamin C, Niacinamide, Aloe vera",
      benefits: "Benefits: Brightens dull skin, fades uneven tone, energizes with natural citrus antioxidants, leaves skin fresh and glowing.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Agrume Orange Mask"),
    },
    {
      name: "Eudora Grenade Pomegranate Mask",
      desc: "An antioxidant-rich mask for firmness and protection.",
      ingredients: "Ingredients: Pomegranate extract, Vitamin E, Peptides, Hyaluronic acid",
      benefits: "Benefits: Fights free radical damage, supports firmness and elasticity, deeply nourishes, protects against early signs of aging.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Grenade Pomegranate Mask"),
    },
    {
      name: "Eudora Fraîcheur Cucumber Mask",
      desc: "A cooling mask that instantly refreshes and de-puffs.",
      ingredients: "Ingredients: Cucumber extract, Aloe vera, Hyaluronic acid, Witch hazel",
      benefits: "Benefits: Cools and soothes overheated or irritated skin, reduces puffiness, hydrates without heaviness, calms after sun exposure.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Fraîcheur Cucumber Mask"),
    },
    {
      name: "Eudora Pureté Tea Tree Mask",
      desc: "A clarifying mask for clear, balanced skin.",
      ingredients: "Ingredients: Tea tree oil, Niacinamide, Zinc PCA, Aloe vera",
      benefits: "Benefits: Purifies pores, calms breakouts and inflammation, controls excess oil, prevents new blemishes from forming.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Pureté Tea Tree Mask"),
    },
    {
      name: "Eudora Antioxydant Green Tea Mask",
      desc: "A protective mask rich in antioxidants for daily defense.",
      ingredients: "Ingredients: Green tea extract, Niacinamide, Vitamin E, Hyaluronic acid",
      benefits: "Benefits: Shields skin from environmental stress, calms inflammation, controls oil, gently brightens over time.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Antioxydant Green Tea Mask"),
    },
    {
      name: "Eudora Éclat Turmeric Mask",
      desc: "A brightening mask that evens tone and restores glow.",
      ingredients: "Ingredients: Turmeric extract, Vitamin C, Niacinamide, Honey",
      benefits: "Benefits: Brightens dark spots and dullness, calms inflammation, evens overall tone, leaves a natural radiant finish.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Éclat Turmeric Mask"),
    },
    {
      name: "Eudora Douceur Honey Mask",
      desc: "A nourishing mask that deeply hydrates and softens.",
      ingredients: "Ingredients: Raw honey, Hyaluronic acid, Shea butter, Vitamin E",
      benefits: "Benefits: Deeply moisturizes, has natural antibacterial properties, softens rough texture, leaves skin supple and glowing.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "700.00",
      image: img("Eudora Douceur Honey Mask"),
    },
  ],
  "face-scrub": [
    {
      name: "Eudora Cool Cucumber Scrub (Oily Skin)",
      desc: "A cooling, oil-balancing scrub that refreshes without over-stripping.",
      ingredients: "Ingredients: Cucumber extract, Fine sugar granules, Aloe vera, Green tea extract, Witch hazel",
      benefits: "Benefits: Cools and soothes overactive skin, absorbs excess oil, gently removes dead skin without triggering more oil, minimizes the look of pores.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "1450.00",
      image: img("Eudora Cool Cucumber Scrub (Oily Skin)"),
    },
    {
      name: "Eudora Fresh Carrot Scrub (Normal Skin)",
      desc: "A brightening everyday scrub that maintains skin's natural balance.",
      ingredients: "Ingredients: Carrot extract, Oat flour, Honey, Vitamin E, Almond oil",
      benefits: "Benefits: Gently buffs away dullness, boosts natural radiance, nourishes while exfoliating, keeps skin balanced without disrupting it.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "1650.00",
      image: img("Eudora Fresh Carrot Scrub (Normal Skin)"),
    },
    {
      name: "Eudora Rich Coffee Scrub (Dry Skin)",
      desc: "A rich, nourishing scrub that exfoliates while deeply moisturizing.",
      ingredients: "Ingredients: Ground coffee, Shea butter, Coconut oil, Brown sugar, Vitamin E",
      benefits: "Benefits: Buffs away flaky, rough patches, stimulates circulation for a natural glow, deeply moisturizes so skin never feels stripped.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "1350.00",
      image: img("Eudora Rich Coffee Scrub (Dry Skin)"),
    },
    {
      name: "Eudora Soft Oat Scrub (Combination Skin)",
      desc: "A balancing scrub that treats oily and dry zones evenly.",
      ingredients: "Ingredients: Colloidal oatmeal, Honey, Jojoba oil, Aloe vera, Chamomile extract",
      benefits: "Benefits: Calms and exfoliates T-zone oiliness and dry cheeks alike, soothes sensitivity, gently removes dead skin without over-drying.",
      oily: "",
      dry: "",
      normal: "",
      combination: "",
      tag: "❤️",
      price: "1350.00",
      image: img("Eudora Soft Oat Scrub (Combination Skin)"),
    },
  ],
};

/* Each product's image points to a local file path following a
   simple convention: /images/products/<slug-of-name>.jpg
   Drop your real product photos into that folder using matching
   filenames and they'll appear automatically — no other code
   needs to change. Until a file exists at that path, the card
   falls back to the on-brand monogram tile (see ProductImage in
   BeautyCategories.tsx). */
   

export const PRODUCTS: Record<ProductKey, Product[]> = {
  "skin-teen": [
    {
      name: "Eudora Lumière Cleanser",
      desc: "A gentle daily cleanser that clears without stripping",
      ingredients: "Ingredients: Salicylic acid (low %), Niacinamide, Aloe vera, Green tea extract, Vitamin B5 ",
      benefits: "Benefits: Clears excess oil and impurities, keeps pores clear, soothes redness without over-drying",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1150.00",
      image: img("Eudora Lumière Cleanser"),
    },
    {
      name: "Eudora Rosée Toner",
      desc: "A light toning mist to balance and prep skin.",
      ingredients: "Ingredients: Witch hazel (alcohol-free), Niacinamide, Aloe vera, Vitamin B3",
      benefits: "Benefits: Balances oil production, minimizes the look of pores, preps skin to absorb the next steps better.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "950.00",
      image: img("Eudora Rosée Toner"),
    },
    {
      name: "Eudora Clarté Serum",
      desc: "A targeted serum for clarity and even tone.",
      ingredients: "Ingredients: Niacinamide, Vitamin C, Zinc PCA, Licorice root extract",
      benefits: "Benefits: Fades post-acne marks, brightens dull patches, controls shine, calms active breakouts",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1500.00",
      image: img("Eudora Clarté Serum"),
    },
    {
      name: "Eudora Velours Moisturizer",
      desc: "A lightweight, oil-free daily moisturizer.",
      ingredients: "Ingredients: Hyaluronic acid, Vitamin E, Niacinamide, Centella asiatica, Ceramides",
      benefits: "Benefits: Deep hydration without heaviness, strengthens the skin barrier, calms irritation",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1250.00",
      image: img("Eudora Velours Moisturizer"),
    },
    {
      name: "Eudora Éclat Suncream SPF 50",
      desc: "Daily, invisible-finish sun protection.",
      ingredients: "Ingredients: Vitamin C, Vitamin E, Zinc oxide, Niacinamide, Hyaluronic acid",
      benefits: "Benefits: No white cast, protects against dark spots and sun damage, doubles as light hydration",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1890.00",
      image: img("Eudora Éclat Suncream SPF 50"),
    },
    {
      name: "Eudora Baume Lip Balm",
      desc: "A nourishing daily lip balm.",
      ingredients: "Ingredients: Shea butter, Vitamin E, Hyaluronic acid, Sunflower seed oil",
      benefits: "Benefits: Softens and protects lips, locks in moisture, light natural sheen.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "450.00",
      image: img("Eudora Baume Lip Balm"),
    },
  ],
  "skin-divine": [
    {
      name: "Eudora Pureté Gel Cleanser",
      desc: "A deeper daily cleanser with light exfoliation.",
      ingredients: "ngredients: Salicylic acid (higher %), Glycolic acid (low %), Niacinamide, Green tea extract",
      benefits: "Benefits: Clears pores more thoroughly, gently exfoliates dead skin, refines texture over time.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1550.00",
      image: img("Eudora Pureté Gel Cleanser"),
    },
    {
      name: "Eudora Renouveau Exfoliating Toner",
      desc: "An AHA/BHA toner for smoother, brighter skin.",
      ingredients: "Ingredients: Glycolic acid, Lactic acid, Salicylic acid, Niacinamide, Aloe vera",
      benefits: "Benefits: Resurfaces skin, fades dullness and rough texture, helps fade old acne scars and dark spots.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1650.00",
      image: img("Eudora Renouveau Exfoliating Toner"),
    },
    {
      name: "Eudora Éclat Vitamin C Serum",
      desc: "A high-strength brightening serum.",
      ingredients: "Ingredients: Vitamin C (15–20%), Vitamin E, Ferulic acid, Hyaluronic acid",
      benefits: "Benefits: Fades hyperpigmentation and dullness, boosts collagen, strong antioxidant defense against pollution/sun damage.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1990.00",
      image: img("Eudora Éclat Vitamin C Serum"),
    },
    {
      name: "Eudora Velours Moisturizer",
      desc: "A richer daily moisturizer for barrier support.",
      ingredients: "Ingredients: Hyaluronic acid, Ceramides, Vitamin E, Peptides, Squalane",
      benefits: "Benefits: Deep, lasting hydration, repairs barrier stressed by actives like retinol/AHA, keeps skin plump and resilient",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "2100.00",
      image: img("Eudora Velours Moisturizer Glow"),
    },
    {
      name: "Eudora Éclat Suncream SPF 50+",
      desc: "Daily broad-spectrum protection, formulated for melanin-rich skin.",
      ingredients: "Ingredients: Vitamin C, Vitamin E, Zinc oxide, Niacinamide, Hyaluronic acid",
      benefits: "Benefits: No white cast, prevents further pigmentation, protects skin actively renewing from retinol/acids.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "2300.00",
      image: img("Eudora Éclat Suncream SPF 50+ skin"),
    },
    {
      name: "Eudora Contour Eye Cream",
      desc: "A targeted cream for the eye area.",
      ingredients: "Ingredients: Peptides, Caffeine, Hyaluronic acid, Vitamin E, Niacinamide",
      benefits: "Benefits: Reduces puffiness and dark circles, firms delicate skin, hydrates without creasing.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1690.00",
      image: img("Eudora Contour Eye Cream"),
    },
    {
      name: "Eudora Clarté Spot Treatment",
      desc: "A fast-acting treatment for occasional breakouts.",
      ingredients: "Ingredients: Salicylic acid, Niacinamide, Tea tree extract, Zinc PCA",
      benefits: "Benefits: Reduces blemishes quickly, controls oil, minimizes scarring risk.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "1850.00",
      image: img("Eudora Clarté Spot Treatment"),
    },
    {
      name: "Eudora Brume Hydrating Mist",
      desc: "A setting and refreshing mist.",
      ingredients: "Ingredients: Rosewater, Hyaluronic acid, Niacinamide, Vitamin B5",
      benefits: "Benefits: Refreshes and re-hydrates through the day, helps actives absorb, calms redness from exfoliants.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "2550.00",
      image: img("Eudora Brume Hydrating Mist"),
    },
    {
      name: "Eudora Baume Lip Treatment",
      desc: "A repairing lip balm with light plumping effect.",
      ingredients: "Ingredients: Shea butter, Peptides, Vitamin E, Hyaluronic acid",
      benefits: "Benefits: Softens, hydrates, and subtly plumps lips, protects against dryness from active skincare routines.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "750.00",
      image: img("Eudora Baume Lip Treatment"),
    },
  ],
  "skin-golden": [
    {
      name: "⁠Eudora Pureté Cleanser A soft, non-stripping daily cleanser.",
      desc: "",
      ingredients: "Ingredients: Ceramides, Niacinamide, Aloe vera, Glycerin",
      benefits: "Benefits: Cleanses without disturbing the barrier — important once retinol is in the routine.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "1950.00",
      image: img("⁠Eudora Pureté Cleanser"),
    },
    {
      name: "⁠⁠Eudora Éclat Vitamin C Serum A potent morning brightening serum.",
      desc: "",
      ingredients: "Ingredients: Vitamin C (20%), Vitamin E, Ferulic acid, Hyaluronic acid",
      benefits: "Benefits: Fades dark spots and dullness, boosts collagen production, antioxidant shield against daily sun/pollution damage.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "2800.00",
      image: img("⁠Eudora Éclat Vitamin"),
    },
    {
      name: "Eudora Velours Day Moisturizer A collagen-supporting daytime moisturizer.",
      desc: "",
      ingredients: "Ingredients: Marine collagen, Hyaluronic acid, Peptides, Niacinamide",
      benefits: "Benefits: Firms and plumps skin, locks in hydration, supports elasticity through the day.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "2115.00",
      image: img("Eudora Velours Day Moisturizer"),
    },
    {
      name: "⁠Eudora Éclat Suncream SPF 50+ Daily broad-spectrum protection for melanin-rich skin.",
      desc: "",
      ingredients: "Ingredients: Vitamin E, Zinc oxide, Niacinamide, Hyaluronic acid",
      benefits: "Benefits: No white cast, prevents pigmentation and photoaging, essential protection while using active ingredients.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "2300.00",
      image: img("⁠Eudora Éclat Suncream SPF 50+ Daily"),
    },
    {
      name: "⁠Eudora Contour Eye Cream A firming, brightening eye treatment.",
      desc: "",
      ingredients: "Ingredients: Peptides, Caffeine, Vitamin E, Hyaluronic acid",
      benefits: "Benefits: Reduces puffiness and dark circles, firms the delicate eye area, hydrates without creasing.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "2550.00",
      image: img("⁠Eudora Contour Eye Cream A firming"),
    },
    {
      name: "Eudora Nuit Cleansing Balm A richer evening cleanser to remove makeup/SPF.",
      desc: "",
      ingredients: "Ingredients: Squalane, Ceramides, Shea butter, Aloe vera",
      benefits: "Benefits: Deep, gentle cleanse that preps skin without over-drying before retinol.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "3100.00",
      image: img("Eudora Nuit Cleansing Balm"),
    },
    {
      name: "Eudora Renouveau Retinol Serum An advanced nightly retinol treatment.",
      desc: "",
      ingredients: "Ingredients: Retinol (0.3–0.5%), Squalane, Ceramides, Hyaluronic acid",
      benefits: "Benefits: Accelerates cell renewal, smooths fine lines and wrinkles, improves texture and tone — no vitamin C, so it stays stable and gentle.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "3750.00",
      image: img("Eudora Renouveau Retinol Serum"),
    },
    {
      name: "⁠Eudora Fermeté Collagen Serum A firming serum focused on elasticity.",
      desc: "",
      ingredients: "Ingredients: Hydrolyzed collagen, Peptides, Hyaluronic acid, Centella asiatica",
      benefits: "Benefits: Restores firmness and bounce, supports skin structure, reduces sagging over time — layers safely under retinol.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "2650.00",
      image: img("⁠Eudora Fermeté Collagen Serum"),
    },
    {
      name: "⁠Eudora Nuit Repair Cream A rich overnight moisturizer to support barrier recovery.",
      desc: "",
      ingredients: "Ingredients: Ceramides, Peptides, Squalane, Niacinamide",
      benefits: "Benefits: Repairs and hydrates overnight, buffers any retinol irritation, keeps skin resilient.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "2990.00",
      image: img("⁠Eudora Nuit Repair Cream moisturizer"),
    },
    {
      name: "⁠Eudora Renaissance Overnight Mask A weekly intensive renewal mask.",
      desc: "",
      ingredients: "Ingredients: Peptides, Collagen, Hyaluronic acid, Centella asiatica",
      benefits: "Benefits: Deep repair and firming boost, wakes up to smoother, plumper skin.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "1700.00",
      image: img("⁠Eudora Renaissance Overnight Mask"),
    },
    {
      name: "⁠Eudora Renouveau Exfoliating Toner A gentle AHA/BHA toner (use only on non-retinol nights).",
      desc: "",
      ingredients: "Ingredients: Glycolic acid, Lactic acid, Niacinamide, Aloe vera",
      benefits: "Benefits: Resurfaces skin, fades texture and dark spots, preps skin for better absorption.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Anytime",
      price: "1850.00",
      image: img("⁠Eudora Renouveau Exfoliating Toner AHA/BHA"),
    },
    {
      name: "Eudora Baume Lip Treatment A repairing, plumping lip balm.",
      desc: "",
      ingredients: "Ingredients: Shea butter, Peptides, Collagen, Vitamin E",
      benefits: "Benefits: Deeply nourishes, softens fine lines around lips, subtle plumping effect.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Anytime",
      price: "750.00",
      image: img("Eudora Baume Lip Treatment lip balm"),
    },
  ],
  "skin-timeless": [
    {
      name: "⁠Eudora Pureté Cleanser — by skin type",
      desc: "",
      ingredients: "",
      benefits: "Benefits (all): Cleanses without disturbing the barrier, preps skin for active serums.",
      oily:"Oily: Niacinamide, Salicylic acid (low %), Aloe vera, Green tea extract — controls shine without over-drying mature skin.",
      dry: "Dry: Ceramides, Squalane, Glycerin, Aloe vera — cream-based, no foaming agents, won't strip.",
      normal: "Normal: Ceramides, Niacinamide, Aloe vera, Glycerin — balanced, gentle daily cleanse.",
      combination:"Combination: Niacinamide, Ceramides, Green tea extract, Glycerin — balances T-zone oil while keeping cheeks comfortable.",
      tag:"Morning",
      price: "1990.00",
      image: img("⁠Eudora Pureté Cleanser — by skin type"),
    },
    {
      name: "Eudora Éclat Vitamin C Serum",
      desc: "",
      ingredients: "Ingredients: Vitamin C (15–20%), Vitamin E, Ferulic acid, Hyaluronic acid",
      benefits: "Benefits: Fades age spots and dullness, boosts collagen, antioxidant defense against sun/pollution — same formula suits all skin types.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "3950.00",
      image: img("Eudora Éclat Vitamin C Serum Hyaluronic acid"),
    },
    {
      name: "Eudora Fermeté Day Moisturizer — by skin type",
      desc: "",
      ingredients: "Ingredients: Vitamin C (15–20%), Vitamin E, Ferulic acid, Hyaluronic acid",
      benefits: "Benefits (all): Firms, plumps, and supports elasticity through the day.",
      oily:"Oily: Niacinamide, Hyaluronic acid, Peptides, Squalane (lightweight) — firms without heaviness.",
      dry: "Dry: Marine collagen, Ceramides, Shea butter, Hyaluronic acid — richer, deeply nourishing.",
      normal: "Normal: Marine collagen, Hyaluronic acid, Peptides, Ceramides — balanced daily firming.",
      combination:"Combination: Peptides, Niacinamide, Hyaluronic acid, Ceramides — lightweight in feel, still firming.",
      tag:"Morning",
      price: "2200.00",
      image: img("Eudora Fermeté Day Moisturizer — by skin type"),
    },
    {
      name: "Eudora Éclat Suncream SPF 50+",
      desc: "",
      ingredients: "Ingredients: Vitamin E, Zinc oxide, Niacinamide, Hyaluronic acid",
      benefits: "Benefits: No white cast on deeper tones, prevents further pigmentation and photoaging — essential with retinol use.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "1995.00",
      image: img("Eudora Éclat Suncream SPF 50+ Hyaluronic acid"),
    },
    {
      name: "⁠Eudora Contour Eye Cream",
      desc: "",
      ingredients: "Ingredients: Peptides, Caffeine, Collagen, Hyaluronic acid",
      benefits: "Benefits: Targets crepiness, puffiness, and dark circles; firms the most delicate skin on the face.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Morning",
      price: "1250.00",
      image: img("⁠Eudora Contour Eye Cream Hyaluronic acid"),
    },
    {
      name: "⁠Eudora Nuit Cleansing Balm",
      desc: "",
      ingredients: "Ingredients: Squalane, Ceramides, Shea butter, Aloe vera",
      benefits: "Benefits: Removes makeup/SPF gently, won't strip mature skin before retinol.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "1700.00",
      image: img("⁠Eudora Nuit Cleansing Balm Aloe vera"),
    },
    {
      name: "Eudora Renouveau Retinol Serum",
      desc: "",
      ingredients: "Ingredients: Retinol (0.5–1%), Squalane, Ceramides, Hyaluronic acid",
      benefits: "Benefits: Higher strength than the 25–45 line for more visible renewal — smooths deeper lines, fades age spots, improves firmness. No vitamin C in the formula, so it stays stable.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "2650.00",
      image: img("Eudora Renouveau Retinol Serum acid"),
    },
    {
      name: "Eudora Fermeté Collagen Serum",
      desc: "",
      ingredients: "Ingredients: Hydrolyzed collagen, Peptides, Hyaluronic acid, Centella asiatica",
      benefits: "Benefits: Restores firmness and bounce, layers safely under retinol, supports sagging skin structure.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "2590.00",
      image: img("Eudora Fermeté Collagen Serum asiatica"),
    },
    {
      name: "⁠Eudora Nuit Repair Cream — by skin type",
      desc: "",
      ingredients: "",
      benefits: "Benefits (all): Buffers retinol irritation, repairs overnight, keeps skin resilient.",
      oily:"Oily: Peptides, Niacinamide, Squalane, Hyaluronic acid (gel-cream texture) — repairs without clogging.",
      dry: "Dry: Ceramides, Shea butter, Squalane, Peptides (balm texture) — intensive overnight nourishment.",
      normal: "Normal: Ceramides, Peptides, Squalane, Hyaluronic acid — balanced overnight repair.",
      combination:"Combination: Ceramides, Niacinamide, Peptides, Hyaluronic acid — repairs barrier evenly across zones.",
      tag:"Evening",
      price: "58",
      image: img("⁠⁠Eudora Nuit Repair Cream — by skin type"),
    },
    {
      name: "Eudora Renaissance Overnight Mask",
      desc: "",
      ingredients: "Ingredients: Peptides, Collagen, Hyaluronic acid, Centella asiatica",
      benefits: "Benefits: Weekly deep repair and firming boost for tired, mature skin.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Evening",
      price: "58",
      image: img("⁠Eudora Renaissance Overnight Mask skin"),
    },
    {
      name: "Eudora Renouveau Exfoliating Toner",
      desc: "",
      ingredients: "Ingredients: Glycolic acid, Lactic acid, Niacinamide, Aloe vera",
      benefits: "Benefits: Gently resurfaces, fades age spots and rough texture — use only on non-retinol nights.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Anytime",
      price: "58",
      image: img("Eudora Renouveau Exfoliating Toner acid"),
    },
    {
      name: "Eudora Baume Lip Treatment",
      desc: "",
      ingredients: "Ingredients: Shea butter, Peptides, Collagen, Vitamin E",
      benefits: "Benefits: Deeply nourishes thinning, drier lips typical at this age; softens lip lines.",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"Anytime",
      price: "58",
      image: img("Eudora Baume Lip Treatment lines"),
    },
  ],
  "body-teen": [
    {
      name: "Fresh Bloom Body Wash",
      desc: "Gentle citrus wash that keeps skin fresh, not dry.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "14",
      image: img("Fresh Bloom Body Wash"),
    },
    {
      name: "Citrus Balance Lotion",
      desc: "Fast-absorbing lotion for active, everyday days.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "16",
      image: img("Citrus Balance Lotion"),
    },
  ],
  "body-divine": [
    {
      name: "Silk Bloom Body Butter",
      desc: "Whipped butter that softens without feeling heavy.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "26",
      image: img("Silk Bloom Body Butter"),
    },
    {
      name: "Radiance Body Oil",
      desc: "Dry oil that leaves a soft, healthy sheen.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "24",
      image: img("Radiance Body Oil"),
    },
  ],
  "body-golden": [
    {
      name: "Firming Gold Cream",
      desc: "Elasticity-support cream for décolletage & body.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "36",
      image: img("Firming Gold Cream"),
    },
    {
      name: "Contour Renewal Scrub",
      desc: "Exfoliating scrub that smooths and refines texture.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "30",
      image: img("Contour Renewal Scrub"),
    },
  ],
  "body-timeless": [
    {
      name: "Nourish Deep Balm",
      desc: "Rich, slow-melt balm for very dry mature skin.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "42",
      image: img("Nourish Deep Balm"),
    },
    {
      name: "Velvet Repair Butter",
      desc: "Overnight butter for elbows, knees & heels.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "40",
      image: img("Velvet Repair Butter"),
    },
  ],
  "hair-teen": [
    {
      name: "Clarity Shampoo",
      desc: "Balances oily roots without drying the lengths.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "15",
      image: img("Clarity Shampoo"),
    },
    {
      name: "Light Bloom Conditioner",
      desc: "Weightless conditioner for fine, young hair.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "15",
      image: img("Light Bloom Conditioner"),
    },
  ],
  "hair-divine": [
    {
      name: "Glow Shine Serum",
      desc: "Frizz-taming serum with a glassy finish.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "22",
      image: img("Glow Shine Serum"),
    },
    {
      name: "Hydra Bloom Mask",
      desc: "Weekly mask for soft, bouncy strands.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "26",
      image: img("Hydra Bloom Mask"),
    },
  ],
  "hair-golden": [
    {
      name: "Strength Renewal Oil",
      desc: "Fortifying oil for thinning or brittle strands.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "32",
      image: img("Strength Renewal Oil"),
    },
    {
      name: "Volume Revive Shampoo",
      desc: "Builds body back into flattened, tired hair.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "28",
      image: img("Volume Revive Shampoo"),
    },
  ],
  "hair-timeless": [
    {
      name: "Silver Grace Shampoo",
      desc: "Brightens grey and silver tones, no yellowing.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "34",
      image: img("Silver Grace Shampoo"),
    },
    {
      name: "Deep Restore Mask",
      desc: "Intensive mask for dry, mature hair.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "38",
      image: img("Deep Restore Mask"),
    },
  ],
  "foot-teen": [
    {
      name: "Fresh Step Scrub",
      desc: "Light exfoliant for smooth, active feet.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "12",
      image: img("Fresh Step Scrub"),
    },
    {
      name: "Cooling Foot Gel",
      desc: "Refreshing gel for feet on the move.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "13",
      image: img("Cooling Foot Gel"),
    },
  ],
  "foot-divine": [
    {
      name: "Soft Bloom Foot Cream",
      desc: "Daily cream that keeps soles soft & smooth.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "18",
      image: img("Soft Bloom Foot Cream"),
    },
    {
      name: "Silk Sole Balm",
      desc: "Overnight balm for silky, cared-for feet.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "19",
      image: img("Silk Sole Balm"),
    },
  ],
  "foot-golden": [
    {
      name: "Renewal Heel Butter",
      desc: "Rich butter for hard-working, tired heels.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "22",
      image: img("Renewal Heel Butter"),
    },
    {
      name: "Golden Sole Repair",
      desc: "Repair cream for cracks and rough patches.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "24",
      image: img("Golden Sole Repair"),
    },
  ],
  "foot-timeless": [
    {
      name: "Deep Comfort Balm",
      desc: "Cushioning balm for sensitive mature skin.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "26",
      image: img("Deep Comfort Balm"),
    },
    {
      name: "Timeless Sole Elixir",
      desc: "Restorative oil blend for very dry feet.",
      ingredients: "",
      benefits: "",
      oily:"",
      dry: "",
      normal: "",
      combination:"",
      tag:"❤️",
      price: "28",
      image: img("Timeless Sole Elixir"),
    },
  ],
};
